site_name: EasyConfig Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  features:
    - content.code.copy
    - navigation.sections

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
